package com.gk.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 * @author Gangadhar, Kasturi
 *
 */
@Entity
@ApiModel(description="Info about Motorbike ") //used for api doc - swagger to define the info about this class
public class MotorBike {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(notes="BIKE id will be generated by hibernate")//swagger documentation about this property
	private int bikeId;

	@Size(max=5,min=2,message="chassis num should be in between 2 to 5 chars") //validation for size of min , max values in request.
	private String chassisNo;

	@NotNull(message="manufacturer must not be null") //javax validation to not allow null values in request.
			//this is not related database.. purely for validations.
	@ApiModelProperty(notes="Manufacturer name must not be null") //swagger documenttion about this property
	private String manufacturer;

	private String engineNo;

	private String model;

	public String getChassisNo() {
		return chassisNo;
	}

	public void setChassisNo(String chassisNo) {
		this.chassisNo = chassisNo;
	}

	public String getManufacturer() {
		return manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getEngineNo() {
		return engineNo;
	}

	public void setEngineNo(String engineNo) {
		this.engineNo = engineNo;
	}

	public int getBikeId() {
		return bikeId;
	}

	public void setBikeId(int bikeId) {
		this.bikeId = bikeId;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Override
	public String toString() {
		return "MotorBike [chassisNo=" + chassisNo + ", manufacturer=" + manufacturer + ", engineNo=" + engineNo
				+ ", bikeId=" + bikeId + ", model=" + model + "]";
	}
}
