spring:
  profiles:
    active: qa

---   
spring:
  profiles: dev
    
    

server:
  port: 9091
course:
  chapterCount : 5
  college: Osmania University
  name: Spring Maven
  duration: 60 days
default:
  course:
      name: My defalut course
      chapterCount: 22
      
---
spring:
  profiles:qa

server:
  port: 9093
course:
  chapterCount : 6
  college: Osmania University_
  name: Spring Maven_
  duration: 60 days_
default:
  course:
      name: My defalut course_
      chapterCount: 21
      